### PR TITLE
A little improvements

### PR DESCRIPTION
**Pull request by vladkalyuzhny**
1. Added in example runtime request of permissions for android marshmallow
2. Added auto mode for taking picture in library

### CODE REVIEW

**Comment by ragnraok** [comment]
the auto mode for the flash setting is not always reliable in all devices, so the original design I only support the FLASH_MODE_TORCH which makes the flash always available when taking picture

**Comment by EzequielAdrianM** [comment]
How can I detect if the device supports FLASH AUTO or not?

**Comment by ragnraok** [comment]
[Camera.Parameters.getSupportedFlashModes()](https://developer.android.com/reference/android/hardware/Camera.Parameters.html#getSupportedFlashModes%28%29)

**Comment by vladkalyuzhny** [comment]
ok. you are right
please add runtime request in example for permissions because now it produces bad user performance for android 6+
thank you for feedback
i like rx and this library because it uses it)
very interesting question: are you planning of adding video capturing functionality?
how to realize this?
do you think about supporting android.hardware.camera2 API?

**Comment by ragnraok** [comment]
@mr-cpp video capturing is pretty complicated in android, and only after API 18+ android implement a useable hardware compress API

for the camera2, currently not all devices support it, and it may need the developer to query how many API it can support on this device: http://source.android.com/devices/camera/versioning.html#camera_api2_capabilities_and_support_levels

**Pull request closed without merging**
